package com.gibsonruitiari.asobi.ui.uiModels

import android.graphics.Color
import com.gibsonruitiari.asobi.data.datamodels.Genres

data class UiGenreModel(val genreName:String, val genreColor:Int=Color.parseColor(""))
fun Genres.toUiGenreModel():UiGenreModel = when(this){
    Genres.MARVEL -> UiGenreModel("$genreName\n$emoji", genreColor = "#DC8665".toColor() )
    Genres.DC_COMICS -> UiGenreModel("$genreName\n$emoji", genreColor = "#138086".toColor() )
    Genres.ACTION -> UiGenreModel("$genreName\n$emoji", genreColor = "#CD7672".toColor() )
    Genres.ADVENTURE ->UiGenreModel("$genreName\n$emoji", genreColor = "#EEB462".toColor() )
    Genres.ANTHOLOGY -> UiGenreModel("$genreName\n$emoji", genreColor = "#8B4C70".toColor() )
    Genres.ANTHROPOMORPHIC -> UiGenreModel("$genreName\n$emoji", genreColor = "#F9C449".toColor() )
    Genres.BIOGRAPHY -> UiGenreModel("$genreName\n$emoji", genreColor = "#3C4CAD".toColor() )
    Genres.CHILDREN -> UiGenreModel("$genreName\n$emoji", genreColor = "#4ADEDE".toColor() )
    Genres.COMEDY -> UiGenreModel("$genreName\n$emoji", genreColor = "#787FF6".toColor() )
    Genres.HORROR -> UiGenreModel(genreName, genreColor = "#1CA7EC".toColor() )
    Genres.DRAMA -> UiGenreModel("$genreName\n$emoji", genreColor = "#7BE495".toColor() )
    Genres.FANTASY -> UiGenreModel("$genreName\n$emoji", genreColor = "#56C596".toColor() )
    Genres.FAMILY ->UiGenreModel("$genreName\n$emoji", genreColor = "#329D9C".toColor() )
    Genres.FIGHTING -> UiGenreModel("$genreName\n$emoji", genreColor = "#68B2A0".toColor() )
    Genres.GRAPHIC_NOVELS -> UiGenreModel(genreName, genreColor = "#384E78".toColor() )
    Genres.HISTORICAL -> UiGenreModel("$genreName\n$emoji", genreColor = "#FA9284".toColor() )
    Genres.LEADING_LADIES -> UiGenreModel("$genreName\n$emoji", genreColor = "#88CDF6".toColor() )
    Genres.LITERATURE -> UiGenreModel("$genreName\n$emoji", genreColor = "#E06C78".toColor() )
    Genres.MAGIC -> UiGenreModel("$genreName\n$emoji", genreColor = "#5874DC".toColor() )
    Genres.MANGA -> UiGenreModel("$genreName\n$emoji", genreColor = "#7697A0".toColor() )
    Genres.MARTIAL_ARTS -> UiGenreModel("$genreName\n$emoji", genreColor = "#94B0B7".toColor() )
    Genres.MATURE -> UiGenreModel("$genreName\n$emoji", genreColor = "#0191B4".toColor() )
    Genres.MILITARY -> UiGenreModel("$genreName\n$emoji", genreColor = "#F8D90F".toColor() )
    Genres.MYSTERY -> UiGenreModel("$genreName\n$emoji", genreColor = "#D3DD18".toColor() )
    Genres.MYTHOLOGY ->UiGenreModel("$genreName\n$emoji", genreColor = "#FE7A15".toColor() )
    Genres.POLITICAL -> UiGenreModel("$genreName\n$emoji", genreColor = "#2D82B5".toColor() )
    Genres.POST_APOCALYPTIC -> UiGenreModel("$genreName\n$emoji", genreColor = "#FB6602".toColor() )
    Genres.PULP -> UiGenreModel("$genreName\n$emoji", genreColor = "#EA4492".toColor() )
    Genres.SCI_FI -> UiGenreModel("$genreName\n$emoji", genreColor = "#FF9CDA".toColor() )
    Genres.ROMANCE -> UiGenreModel("$genreName\n$emoji", genreColor = "#004E9A".toColor() )
    Genres.ROBOTS -> UiGenreModel("$genreName\n$emoji", genreColor = "#428CD4".toColor() )
    Genres.SPY -> UiGenreModel("$genreName\n$emoji", genreColor = "#63BCC9".toColor() )
    Genres.CRIME -> UiGenreModel(genreName, genreColor = "#FFBE88".toColor() )
    Genres.SUPERHERO -> UiGenreModel("$genreName\n$emoji", genreColor = "#5D6E1E".toColor() )
    Genres.SUPERNATURAL -> UiGenreModel("$genreName\n$emoji", genreColor = "#8A5082".toColor() )
    Genres.SUSPENSE -> UiGenreModel("$genreName\n$emoji", genreColor = "#A5CAD2".toColor() )
    Genres.SCIENCE_FICTION -> UiGenreModel("$genreName $emoji", genreColor = "#FFAA47".toColor() )
    Genres.SLICE_OF_LIFE -> UiGenreModel(genreName, genreColor = "#F54D28".toColor() )
    Genres.THRILLER -> UiGenreModel("$genreName\n$emoji", genreColor = "#704968".toColor() )
    Genres.VAMPIRES -> UiGenreModel("$genreName\n$emoji", genreColor = "#A7D676".toColor() )
    Genres.VIDEO_GAMES -> UiGenreModel("$genreName\n$emoji", genreColor = "#CCABD8".toColor() )
    Genres.WAR -> UiGenreModel("$genreName\n$emoji", genreColor = "#B4574E".toColor() )
    Genres.WESTERN -> UiGenreModel("$genreName\n$emoji", genreColor = "#8A5082".toColor() )
    Genres.ZOMBIES -> UiGenreModel("$genreName\n$emoji", genreColor = "#FFC98B".toColor() )
}
private  fun String.toColor():Int=Color.parseColor(this)