package com.gibsonruitiari.asobi.ui.uiModels

import android.graphics.Color
import com.gibsonruitiari.asobi.data.datamodels.Genres

data class UiGenreModel(val genreName:String, val genreColor:Int=Color.parseColor(""))
fun Genres.toUiGenreModel():UiGenreModel = when(this){
    Genres.MARVEL -> UiGenreModel(genreName, genreColor = "#DC8665".toColor() )
    Genres.DC_COMICS -> UiGenreModel(genreName, genreColor = "#138086".toColor() )
    Genres.ACTION -> UiGenreModel(genreName, genreColor = "#CD7672".toColor() )
    Genres.ADVENTURE ->UiGenreModel(genreName, genreColor = "#EEB462".toColor() )
    Genres.ANTHOLOGY -> UiGenreModel(genreName, genreColor = "#8B4C70".toColor() )
    Genres.ANTHROPOMORPHIC -> UiGenreModel(genreName, genreColor = "#F9C449".toColor() )
    Genres.BIOGRAPHY -> UiGenreModel(genreName, genreColor = "#3C4CAD".toColor() )
    Genres.CHILDREN -> UiGenreModel(genreName, genreColor = "#4ADEDE".toColor() )
    Genres.COMEDY -> UiGenreModel(genreName, genreColor = "#787FF6".toColor() )
    Genres.HORROR -> UiGenreModel(genreName, genreColor = "#1CA7EC".toColor() )
    Genres.DRAMA -> UiGenreModel(genreName, genreColor = "#7BE495".toColor() )
    Genres.FANTASY -> UiGenreModel(genreName, genreColor = "#56C596".toColor() )
    Genres.FAMILY ->UiGenreModel(genreName, genreColor = "#329D9C".toColor() )
    Genres.FIGHTING -> UiGenreModel(genreName, genreColor = "#68B2A0".toColor() )
    Genres.GRAPHIC_NOVELS -> UiGenreModel(genreName, genreColor = "#384E78".toColor() )
    Genres.HISTORICAL -> UiGenreModel(genreName, genreColor = "#FA9284".toColor() )
    Genres.LEADING_LADIES -> UiGenreModel(genreName, genreColor = "#88CDF6".toColor() )
    Genres.LITERATURE -> UiGenreModel(genreName, genreColor = "#E06C78".toColor() )
    Genres.MAGIC -> UiGenreModel(genreName, genreColor = "#5874DC".toColor() )
    Genres.MANGA -> UiGenreModel(genreName, genreColor = "#7697A0".toColor() )
    Genres.MARTIAL_ARTS -> UiGenreModel(genreName, genreColor = "#94B0B7".toColor() )
    Genres.MATURE -> UiGenreModel(genreName, genreColor = "#0191B4".toColor() )
    Genres.MILITARY -> UiGenreModel(genreName, genreColor = "#F8D90F".toColor() )
    Genres.MYSTERY -> UiGenreModel(genreName, genreColor = "#D3DD18".toColor() )
    Genres.MYTHOLOGY ->UiGenreModel(genreName, genreColor = "#FE7A15".toColor() )
    Genres.POLITICAL -> UiGenreModel(genreName, genreColor = "#2D82B5".toColor() )
    Genres.POST_APOCALYPTIC -> UiGenreModel(genreName, genreColor = "#FB6602".toColor() )
    Genres.PULP -> UiGenreModel(genreName, genreColor = "#EA4492".toColor() )
    Genres.SCI_FI -> UiGenreModel(genreName, genreColor = "#FF9CDA".toColor() )
    Genres.ROMANCE -> UiGenreModel(genreName, genreColor = "#004E9A".toColor() )
    Genres.ROBOTS -> UiGenreModel(genreName, genreColor = "#428CD4".toColor() )
    Genres.SPY -> UiGenreModel(genreName, genreColor = "#63BCC9".toColor() )
    Genres.CRIME -> UiGenreModel(genreName, genreColor = "#FFBE88".toColor() )
    Genres.SUPERHERO -> UiGenreModel(genreName, genreColor = "#CDB3D4".toColor() )
    Genres.SUPERNATURAL -> UiGenreModel(genreName, genreColor = "#8A5082".toColor() )
    Genres.SUSPENSE -> UiGenreModel(genreName, genreColor = "#A5CAD2".toColor() )
    Genres.SCIENCE_FICTION -> UiGenreModel(genreName, genreColor = "#6F590".toColor() )
    Genres.SLICE_OF_LIFE -> UiGenreModel(genreName, genreColor = "#A5678E".toColor() )
    Genres.THRILLER -> UiGenreModel(genreName, genreColor = "#E8B7D4".toColor() )
    Genres.VAMPIRES -> UiGenreModel(genreName, genreColor = "#A7D676".toColor() )
    Genres.VIDEO_GAMES -> UiGenreModel(genreName, genreColor = "#F9E2AE".toColor() )
    Genres.WAR -> UiGenreModel(genreName, genreColor = "#A8DEE0".toColor() )
    Genres.WESTERN -> UiGenreModel(genreName, genreColor = "#8A5082".toColor() )
    Genres.ZOMBIES -> UiGenreModel(genreName, genreColor = "#6F590".toColor() )
}
private  fun String.toColor():Int=Color.parseColor(this)